import uuid
from django.db import models
from onboarding.models import Company
from b2b_admin.models import Client, Driver
from logistics.models import Product, Warehouse

class Order(models.Model):
    STATUS_CHOICES = [
        ('PLACED', 'Order Placed'),
        ('DISPATCHED', 'Dispatched'),
        ('IN_TRANSIT', 'In Transit'),
        ('DELIVERED', 'Delivered'),
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order_number = models.CharField(max_length=50, unique=True)
    company = models.ForeignKey(Company, on_delete=models.PROTECT, related_name='orders')
    client = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='orders')
    
    destination_address = models.TextField()
    destination_lat = models.FloatField(null=True, blank=True)
    destination_lng = models.FloatField(null=True, blank=True)
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PLACED', db_index=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    
    def __str__(self):
        return f"{self.order_number} - {self.client.name}"

class OrderItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.quantity} x {self.product.sku} for {self.order.order_number}"

class Shipment(models.Model):
    STATUS_CHOICES = [
        ('ACTIVE', 'Active (Assigned)'),
        ('IN_TRANSIT', 'In Transit (Driving)'),
        ('PENDING_APPROVAL', 'Pending Proof Approval'),
        ('COMPLETED', 'Completed'),
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='shipment')
    driver = models.ForeignKey(Driver, on_delete=models.PROTECT, related_name='shipments')
    
    # JSONField to store the geojson route array generated by Leaflet Routing Machine
    route_geo_json = models.JSONField(null=True, blank=True)
    
    current_lat = models.FloatField(null=True, blank=True)
    current_lng = models.FloatField(null=True, blank=True)
    
    # New fields for tracking and verification
    estimated_duration = models.CharField(max_length=50, null=True, blank=True)
    estimated_delivery_time = models.DateTimeField(null=True, blank=True)
    proof_of_delivery_url = models.CharField(max_length=500, null=True, blank=True)
    vehicle_info = models.CharField(max_length=100, null=True, blank=True)
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='ACTIVE', db_index=True)
    dispatched_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Shipment for {self.order.order_number} by {self.driver.name}"

class Notification(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='notifications')
    message = models.CharField(max_length=255)
    is_read = models.BooleanField(default=False, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.message
